services:
    api:
        build:
            context: .
            dockerfile: api/Dockerfile
            target: production
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production

    web:
        build:
            context: .
            dockerfile: web/Dockerfile
            target: production
        ports:
            - '8080:80'
        depends_on:
            - api
